services:
  sms-server:
    build: .
    container_name: sms-server
    restart: always
    ports:
      - "36001:3000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
      - PORT=3000
